    [tool]
id          = "me.ironfeet.beeper4lightos"
label       = "Beeper4LightOS"
versionCode = 2
versionName = "0.0.2"
serverPackage = "me.ironfeet"
permissions = ["android.permission.INTERNET", "android.permission.POST_NOTIFICATIONS", "android.permission.CAMERA", "android.permission.RECORD_AUDIO"]
